config/routes.rb
Goodlibrary::Application.routes.draw do

  root to: 'books#index'

  get '/register', :to => 'registrations#new'
  post '/register', :to => 'registrations#create'

  get '/sign-in', :to => 'sessions#new', :as => 'sign_in'
  post '/sign-in', :to => 'sessions#create', :as => 'session'
  delete '/sign-in', :to => 'sessions#destroy'

  resources :books, only: [:index, :show] do
    resource :loan, only: [:create, :destroy]
    get 'loan', to: "loans#update"
  end

  get 'my-loans', to: 'books#my_loans', as: 'my_loans'

end

app/models/book.rb
class Book < ActiveRecord::Base

  validates :title, :author, :image_url, :goodreads_url, presence: true

  has_many :loans, dependent: :destroy
  has_many :users, through: :loans

  scope :with_image, -> { where('image_url is NOT ?', 'https://www.goodreads.com/assets/nocover/111x148.png') }
  scope :in_series_alphabetical_order, -> { order('series IS NULL ASC, series ASC') }
  scope :unavailable, -> { includes(:loans).where('loans.out_date is NOT NULL').references(:loans)}
  scope :available, -> { where("id not IN (?)", Loan.active.collect(&:book_id))}

  def available?
    !Loan.on_loan?(self)
  end
end

app/models/loan.rb
class Loan < ActiveRecord::Base

  belongs_to :book
  belongs_to :user

  validates :book_id, :user_id, presence: true

  scope :active, -> { where(in_date: nil) }

  class << self
    def lend(book, user)
      find_or_create_by!(book: book, user: user, out_date: Date.today, in_date: nil)
    end

    def lended_to?(book, user)
      return false if book.nil? || user.nil?
      where(book_id: book.id, user_id: user.id, in_date: nil).present?
    end

    def on_loan?(book)
      return false if book.nil?
      where(book_id: book.id, in_date: nil).present?
    end

    def return_loan(book, user)
      loan = find_by(book: book, user: user, in_date: nil)
      loan.update_attributes!(in_date: Date.today)
    end
  end
end

app/models/shelf_import.rb
require 'faraday'
require 'faraday_middleware'
require 'nokogiri'

class ShelfImport

  def initialize

  end

  def get_shelf
    response = connection.get "/review/list/1222242.xml?key=5pYuYZCH0Glr3oTM9nfwow&v=2&id=1222242&shelf=my-library&per_page=200"
    Nokogiri::XML(response.body).search('book').each do |book_data|
      book = Book.new(
        title: extract_title(book_data.search('title').text),
        series: extract_series(book_data.search('title').text),
        author: book_data.search('author name').first.text,
        image_url: book_data.search('image_url').first.text,
        goodreads_url: book_data.search('link').first.text,
        isbn: book_data.search('isbn').text,
        isbn13: book_data.search('isbn13').text,
        num_pages: book_data.search('num_pages').text,
        format: book_data.search('format').text,
        description: book_data.search('description').text,
        publisher: book_data.search('publisher').text
      )
      book.save!
    end
  end

  def connection
    @connection ||= Faraday.new(url: 'https://www.goodreads.com') do |faraday|
      faraday.adapter Faraday.default_adapter
    end
  end

  def extract_title title
    if title['('].nil?
      title
    else
      title.split('(').first.strip
    end
  end

  def extract_series title
    if !title['('].nil?
      title.split('(').last[0..-2].strip
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :loans
  has_many :books, -> {merge(Loan.active) }, through: :loans

  validates :email, :presence => true, :uniqueness => true, :email => true, :length => { :maximum => 191 }
  validates :first_name, :presence => true, length: { maximum: 255 }
  validates :last_name, :presence => true, length: { maximum: 255 }

  has_secure_password

  class << self
    def authenticate(email, password)
      user = User.find_by_email(email)
      return nil unless user
      user.authenticate(password) ? user : nil
    end
  end

  def full_name
    [first_name, last_name].join(' ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def signed_in?
    current_user.present?
  end

  def current_user
    user = current_user_id && User.find_by_id(current_user_id)
    session['user_id'] = user.id if session['user_id'].blank? && user
    user
  end

  def current_user_id
    session['user_id']
  end

  def sign_in_as(user)
    return_path = session['return_path']
    reset_session
    session.merge!('user_id' => user.id, 'return_path' => return_path)
  end

  def sign_out
    reset_session
  end

  helper_method :current_user, :signed_in?
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    if params[:available]
      @books = Book.with_image.available.in_series_alphabetical_order
    else
      @books = Book.with_image.in_series_alphabetical_order.all
    end
  end

  def show
    @book = Book.find_by_id(params[:id])
  end

  def my_loans
    if signed_in?
      @books = current_user.books
      render 'index'
    else
      redirect_to sign_in_path
    end
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  include PayPal::SDK::REST
  before_filter :lookup_book

  def create
    if signed_in?
      if payment.create
        session[:payment_id] = payment.id
        session[:book_id] = @book.id
        redirect_to payment.links.find{|link| link.method == 'REDIRECT'}.href
      end
    else
      redirect_to sign_in_path
    end
  end

  def update
    return_payment = Payment.find session[:payment_id]
    if return_payment.execute payer_id: params['PayerID']
      loan = Loan.lend(@book, current_user)
      if loan.valid?
        redirect_to book_path(@book)
      else
        redirect_to root_path
      end
    end
  end

  def destroy
    Loan.return_loan(@book, current_user)
    redirect_to book_path(@book)
  end

  private

  def lookup_book
    @book = Book.find_by_id(params[:book_id] || session[:book_id])
  end

  def payment
    @payment ||= Payment.new({
      intent: 'authorize',
      payer: {
        payment_method: 'paypal'
      },
      redirect_urls: {
        return_url: "http://localhost:3000/books/#{@book.id}/loan",
        cancel_url: "http://localhost:3000/books/#{@book.id}/loan"
      },
      transactions: [
        {
          amount: {
            total: "5.00",
            currency: "GBP"
          },
          description: "Late fees for GoodLibrary"
        }
      ]
    })
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.persisted?
      sign_in_as @user
      redirect_to root_path
    else
      @user.password_confirmation = user_params[:password_confirmation]
      render :new
    end
  end

  private

  def user_params
    params[:user].permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to(root_path) if signed_in?
  end

  def create
    if signed_in?
      redirect_to root_path
    else
      if user = User.authenticate(params[:email], params[:password])
        sign_in_as user
        redirect_to root_path
      else
        sign_out
        render :new
      end
    end
  end

  def destroy
    if signed_in?
      sign_out
    end
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def book_image_tag(book, css_class = nil)
    image_tag book.image_url, alt: book.title, title: book.title, class: css_class
  end
end

app/helpers/form_helper.rb
module FormHelper

  def control_group_for(object, method, &block)
    control_group_class = 'controlgroup'
    control_group_class += ' error' if object.errors[method].any?
    content_tag(:div, class: control_group_class, &block)
  end

  def error_message_for(object, method)
    return unless object.errors[method].any?
    content_tag(:span, object.errors[method].to_sentence, class: 'error_message')
  end
end

app/views/books/_book.html.haml
= link_to book_path(book), :class => ['book media', ('book--unavailable' unless book.available?)] do
  .media__img
    =book_image_tag(book)
  .media__body
    %h3.book__heading= book.title
    %p= book.series
    %p= book.author

app/views/books/index.html.haml
.grid<
  - @books.each do |book|
    .grid__item.lap--one-half.desk--one-third>
      = render partial: 'book', locals: {book: book}

app/views/books/show.html.haml
.article
  %h1.article__title= @book.title
  %p.article__subtitle= @book.series

  .grid<
    .grid__item.desk--three-quarters>
      .article__buttons
        - if Loan.lended_to?(@book, current_user)
          = button_to 'Return this book', book_loan_path(@book), method: :delete, class: 'btn btn--small btn--negative'
        - else
          = button_to 'Check out this book', book_loan_path(@book), class: 'btn btn--small'

      .description!= @book.description

    .grid__item.desk--one-quarter>
      %p
        =book_image_tag(@book)

      %p.article__line-item<
        Author:
        %span= @book.author

      %p.article__line-item<
        Format:
        %span= @book.format

      %p.article__line-item<
        Pages:
        %span= @book.num_pages

      %p.article__line-item<
        Rating:
        %span= @book.rating || 'N/A'

      %p.article__line-item<
        Publisher:
        %span= @book.publisher

      - unless @book.isbn.empty?
        %p.article__line-item<
          ISBN:
          %span= @book.isbn.inspect

      %p.article__line-item
        = link_to "GoodReads", @book.goodreads_url

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Goodlibrary</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="main">
  <header class="global-header">
    <%= render 'shared/navigation' %>
  </header>

  <%= yield %>
</div>
</body>
</html>

app/views/shared/_navigation.html.haml
.header-wrapper
  .header-title
    =link_to 'GoodLibrary', '/'

  .header-nav
    %ul.nav.nav--global
      %li
        - if signed_in?
          = "Signed in as #{current_user.first_name}"
          = link_to "My Loans", my_loans_path
          = form_tag(session_path, :method => :delete, class: 'sign-out') do
            = button_tag(content_tag('div', 'Sign out'), class: 'btn btn--small btn--negative')
        - else
          =link_to 'Sign In', sign_in_path, :class => 'btn btn--small'

.header-site-nav
  %ul.nav.nav--global
    %li
      =link_to 'All Books', '/'
      =link_to 'Available Books', books_path(available: 1)